name: Compile Java

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Скачиваем код из репозитория
      - uses: actions/checkout@v4

      # 2. Устанавливаем JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Компилируем все Java-файлы
      - name: Compile
        run: |
          find . -name "*.java" > sources.txt
          if [ -s sources.txt ]; then
            javac @sources.txt
            echo "✅ Compilation OK"
          else
            echo "⚠️ No Java files found"
          fi
